name: Build, test, and publish container image
'on':
  workflow_dispatch: null
  push:
    branches:
      - '*'
env:
  IMG-NAME: ravasimages/test-hostname:latest
  IMG-REGISTERY: hub.docker.com
jobs:
  build:
    name: build & push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: ./docker/
          push: false
          load: true
          tags: ${{ github.run_id }}
      - name: Run Trivy for HIGH,CRITICAL CVEs and report (blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.run_id }}
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL
          format: sarif
          output: trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif
